#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 3 ]]; then
  echo "Usage: $0 <platform> <problem_id> <title>"
  echo "Example: $0 boj 1000 \"A+B\""
  exit 1
fi

platform="$1"
problem_id="$2"
title="$3"

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/.." && pwd)"

problem_dir="$repo_root/archive/$platform/$problem_id"
solutions_dir="$problem_dir/solutions"
problem_md="$problem_dir/problem.md"
template_problem="$repo_root/templates/problem.md"

mkdir -p "$solutions_dir"

if [[ ! -f "$problem_md" ]]; then
  cp "$template_problem" "$problem_md"
  {
    echo ""
    echo "<!-- Generated by scripts/new-problem.sh -->"
    echo "- Platform: $platform"
    echo "- Problem ID: $problem_id"
    echo "- Title: $title"
  } >> "$problem_md"
fi

echo "Created/verified: $problem_dir"
